pipeline{
    agent any
  tools {
      maven 'M3'
    }
    stages {

       stage('BuildCode'){
        steps{
            dir('Example1-master'){
                sh 'mvn clean install'
            }
        }
       }
          stage("upload artifactory")
        {
            steps{
            script{
                sh "git rev-parse --short HEAD> .git/commit-id"
                def commit_id= readFile('.git/commit-id')
                sh "/devops/bin/appendCommitid.sh ${workspace}/Example1-master/target ${commit_id}"
                def branch =load "muleDevopsConfig/BranchDetails.groovy"
                def branchname= branch.getBranchName()

                def server = Artifactory.server 'Artifactorytest'
                  def uploadSpec = """{
                    "files": [
                      {
                        "pattern":"/var/lib/jenkins/workspace/CIPipeline/Example1-master/target/test*.jar",
                        "target": "libs-snapshot-local/${branchname}/",
                        "recursive": "true",
                        "flat": "true"
                    }
                     ]
                    }"""

                  server.upload(uploadSpec)
        }
        }
    }
}
}
