pipeline{
    agent any
  tools {
      maven 'M3'
    }
    environment{
      APPLICATIONNAME="Example1-master"
      ANYPOINTSTUDIO_CREDENTIALS= credentials('anypoint-studio-snjy')
      DEPLOYMENT_TYPE = sh(script: "/devops/bin/checkRunType.sh ${APPLICATIONNAME}", , returnStdout: true).trim()
    }
       stage('BuildCode'){
        steps{
	    	
            dir('Example1-master'){
                sh 'mvn clean install'
            }
        }
       }
          stage("upload artifactory")
        {
            steps{
            script{
                sh "git rev-parse --short HEAD> .git/commit-id"
                def commit_id= readFile('.git/commit-id')
                sh "/devops/bin/appendCommitid.sh ${workspace}/${applicationName}/target ${commit_id}"
                //Creating a artifacts in local server first gives a clear visibility on jenkins builds and later uploading code to jfrog artifactory
                sh "mkdir /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}"
                sh "cp -r ${workspace}/${applicationName}/target/*.jar /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/"
                def branchd =load "muleDevopsConfig/BranchDetails.groovy"
                def branchname= branchd.getBranchName()

                def server = Artifactory.server 'Artifactorytest'
                  def uploadSpec = """{
                    "files": [
                      {
                        "pattern":"/devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/*.jar",
                        "target": "libs-snapshot-local/${branchname}/",
                        "recursive": "true",
                        "flat": "true"
                    }
                     ]
                    }"""

                  server.upload(uploadSpec)
        }
        }
    }
    stage("Deploy") {
        steps {
          script{
            jarName=sh (script : 'ls /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/',returnStdout:true)
            echo "${jarName}"
            def deploy= load "muleDevopsConfig/DeployCloudHub.groovy"
	        deploy.deployToCloudHub(jarName)
          }
        }

    }
}
}
