pipeline{
    agent any
  tools {
      maven 'M3'
    }
    stages {

       stage('BuildCode'){
        steps{
            dir('Example1-master'){
                sh 'mvn clean install'
            }
        }
       }
          stage("upload artifactory")
        {
            steps{
            script{
                sh "git rev-parse --short HEAD> .git/commit-id"
                def commit_id= readFile('.git/commit-id')
                sh "/devops/bin/appendCommitid.sh ${workspace}/Example1-master/target ${commit_id}"
                sh "mkdir /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}"
                sh "cp -r ${workspace}/Example1-master/target/ /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/"
                def branch =load "muleDevopsConfig/BranchDetails.groovy"
                def branchname= branch.getBranchName()

                def server = Artifactory.server 'Artifactorytest'
                  def uploadSpec = """{
                    "files": [
                      {
                        "pattern":"/devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/test*.jar",
                        "target": "libs-snapshot-local/${branchname}/",
                        "recursive": "true",
                        "flat": "true"
                    }
                     ]
                    }"""

                  server.upload(uploadSpec)
        }
        }
    }
    stage("Deploy") {
        steps {
          script{
            jarName=sh (script : 'ls /devops/out/CDScript/working/${BUILD_NUMBER}_${JOB_NAME}/',returnStdout:true)
            prinltn(${jarName});
          }
        }

    }
}
}
